language: node_js
node_js: 8.12.0

before_deploy: "ionic build"

deploy:
  provider: firebase
  token:
    secure: tLrnJq8QsHDOqR1Y3FWEHpp5OB4CgjYXxXONbr2YBm2ydYs0zF9BCWttUxL0bS/8dNxxiTD0x7Kw35ZjGDZvci9MKfUrKDFYbl6+3um3r887OCj8BjvZwZOK7EukNYlWtHxSVXz1/PI5Gc40wQV8brYpta1Sg17d/XCCxP+Nc70VtgzCnfOWNJg8+6GEM8m2gNp1+/eBHA1LLxBshrLFjfEN1XsblarxvRqBsPoFIopoYGLlM/1y+ATiJrCJ8gIozFwr3STTh2o6q8lF1FbH8jxPbP2i7T5cUFdYnG2/2BFW7Hara1HU1wKoOJ5/7FNEDgjE6EtLLZ9zF3O9W/g46Okah+/FEdfE81XJ6rZ7qEzr75rI2EA0CyV617VDtY5C9n7iZQUmXW+/XxE/1Ic4y56ogfaf2sQSFu/MxVKPTqIHUmcIOf+dLWaysSj4N3SmaFHWFCc2zS0dLFP6FbpgOiNtRhdZugAGfNRo4wOa4QLmetKdlp3vWGCqI1Mjh3PVIuIS714JtCegQSUtx87+6SYkP9YKVFloznlJlT/uOQK1MyRRw5YXuEfyy1+/tqY0s2qOAnAdseh4/W2bU2SwTCMBr8A2aEvqe2Cr4bANfmbWPk4zqevp4nQL8FdDnOxvPJ4Af8kkws/qn5bbNELTr27GrpVk4hT1hbqOJGFwaS4=

env:
  global:
    secure: tLrnJq8QsHDOqR1Y3FWEHpp5OB4CgjYXxXONbr2YBm2ydYs0zF9BCWttUxL0bS/8dNxxiTD0x7Kw35ZjGDZvci9MKfUrKDFYbl6+3um3r887OCj8BjvZwZOK7EukNYlWtHxSVXz1/PI5Gc40wQV8brYpta1Sg17d/XCCxP+Nc70VtgzCnfOWNJg8+6GEM8m2gNp1+/eBHA1LLxBshrLFjfEN1XsblarxvRqBsPoFIopoYGLlM/1y+ATiJrCJ8gIozFwr3STTh2o6q8lF1FbH8jxPbP2i7T5cUFdYnG2/2BFW7Hara1HU1wKoOJ5/7FNEDgjE6EtLLZ9zF3O9W/g46Okah+/FEdfE81XJ6rZ7qEzr75rI2EA0CyV617VDtY5C9n7iZQUmXW+/XxE/1Ic4y56ogfaf2sQSFu/MxVKPTqIHUmcIOf+dLWaysSj4N3SmaFHWFCc2zS0dLFP6FbpgOiNtRhdZugAGfNRo4wOa4QLmetKdlp3vWGCqI1Mjh3PVIuIS714JtCegQSUtx87+6SYkP9YKVFloznlJlT/uOQK1MyRRw5YXuEfyy1+/tqY0s2qOAnAdseh4/W2bU2SwTCMBr8A2aEvqe2Cr4bANfmbWPk4zqevp4nQL8FdDnOxvPJ4Af8kkws/qn5bbNELTr27GrpVk4hT1hbqOJGFwaS4=
